- cmd/device-definitions-api/create_tesla_integration.go
- cmd/device-definitions-api/main.go
- internal/core/commands/sync_dd_smart_cart_forward_compatibilty_data.go
- internal/core/common/constants.go
- port command from devices-api
> Add command for create tesla integrations

- internal/infrastructure/metrics/prometheus_metric_service.go
> promauto logging

- internal/api/grpc_service.go
Fix UpdateDeviceDefinitionCommandResult 
GRPC UpdateDeviceDefinition
> conversion fixed

- cmd/device-definitions-api/populate_device_features.go
- internal/infrastructure/db/models/device_integrations.go
- pkg/elastic/query_device_features.go
Persist array of features in db after retrieving from es.
> Use features model to persist features as array in db

- internal/api/grpc_service.go
> Fix Implementation

- internal/api/grpc_service.go
> fix bug where object should be pointer

- internal/api/api.go
- internal/core/queries/get_dd_by_ids.go
- internal/core/queries/get_dd_by_ids_test.go
- pkg/dbtest/test_helper.go
> Device definition api validate arrays

- internal/api/api.go
- internal/api/common/behaviors.go
- internal/core/queries/get_dd_by_id.go
- internal/core/queries/get_dd_by_ids.go
- internal/infrastructure/metrics/prometheus_metric_service.go
> PLA-176 Enable prometheus metrics

- internal/api/grpc_service.go
- internal/core/commands/update_dd.go
- internal/core/commands/update_dd_test.go
- internal/infrastructure/dbtest/test_helper.go
> Device definition api grpc update

- internal/core/models/device_definition_models.go
- internal/core/services/cache_dd.go
CompatibleIntegrations restored
device-definitions/:id
> CompatibleIntegrations restored

- internal/api/grpc_service.go
- internal/core/common/utils.go
- internal/core/models/device_definition_models.go
- internal/core/queries/get_dm_all.go
- internal/core/queries/get_dm_by_name.go
- pkg/grpc/device_definition.pb.go
- pkg/grpc/device_definition.proto
- pkg/grpc/device_definition_grpc.pb.go
> Add DeviceMake Queries

- internal/api/api.go
- internal/api/grpc_service.go
- internal/core/commands/update_dd.go
- internal/core/queries/get_dm_all.go
- internal/core/queries/get_dm_by_name.go
> Added upsert to device definition

- internal/core/common/constants.go
- internal/infrastructure/db/repositories/device_definition_repo.go
- internal/infrastructure/db/repositories/device_definition_repo_test.go
- internal/infrastructure/dbtest/test_helper.go
> PLA-260 Add autopi integration on create DD

- charts/device-definitions-api/values.yaml
- internal/api/grpc_service.go
- internal/infrastructure/db/repositories/device_definition_repo.go
> Small compatibility query tweaks, more logging

- internal/infrastructure/db/migrations/20221006130646_integration_features.sql
The PR adds the rest of the compatibility fields to the integration_features table migration
> EXP-143 Add compatibility fields to integration features migration

- charts/device-definitions-api/templates/cronjob.yaml
- charts/device-definitions-api/values-prod.yaml
- internal/api/grpc_service.go
- internal/core/commands/create_dd.go
- internal/core/commands/update_dd.go
- internal/infrastructure/db/repositories/device_definition_repo.go
- enable cronjobs
- only allow verified to be set to true, so that if already true we don't go back and set it to false
- update some edge case error handling when makeId or deviceTypeId are not found
> PLA-309 Update cronjobs, handle DD verified more carefully

- internal/core/common/utils.go
- internal/core/queries/get_dd_all.go
- internal/core/queries/get_dd_by_source.go
- internal/core/queries/get_dd_group_all.go
- internal/core/queries/get_dd_without_image.go
- internal/core/services/cache_dd.go
- internal/infrastructure/db/repositories/device_definition_repo.go
- internal/infrastructure/db/repositories/mocks/device_definition_repo_mock.go
- return err on util to project to return object if required parameters are not met
- check for err in any use case
> Fix get all panicking

- internal/infrastructure/db/migrations/20221101142239_recalls_index.sql
> Add an index to device_definition_id in recalls

- internal/api/common/behaviors.go
- internal/core/queries/get_dd_all_test.go
- internal/infrastructure/db/repositories/device_definition_repo.go
> Fix query all

- internal/core/common/utils.go
- internal/core/models/device_definition_models.go
- internal/core/queries/get_integ_options.go
- remove property that should not be used anymore
> Deprecate capabilities

- cmd/device-definitions-api/populate_device_features.go
- internal/infrastructure/db/migrations/20221121154535_makes_metadata.sql
- internal/infrastructure/db/models/device_makes.go
> Add device makes metadata

- .golangci.yml
- cmd/device-definitions-api/populate_device_features.go
- go.mod
- go.sum
- if there are multiple regions for an autopi, but one of them has no features set, copy the features from the other region that does have them but set the support level to 1
> EXP-361 features copy region

- cmd/device-definitions-api/populate_device_features.go
- cmd/device-definitions-api/populate_device_features_test.go
- internal/core/commands/sync_dd_smart_cart_compatibility_test.go
- internal/core/commands/sync_dd_smart_cart_forward_compatibilty_data_test.go
- internal/infrastructure/db/repositories/device_definition_repo_test.go
- internal/infrastructure/dbtest/test_helper.go
- previous implementation of this didn't actually work. after digging more and trying things out this version should be better.
- unit test for key functionality of region feature copying
> EXP-361 Copy region feature data improvements and fixes

- cmd/device-definitions-api/fuel_image_service.go
- internal/core/commands/update_dd_image.go
- internal/infrastructure/db/migrations/20230120125939_images_timestamps.sql
- internal/infrastructure/db/models/images.go
> EXP-238 add created on updated on, fix upsert bug, logging

- README.md
> minor tweaks for opensourcing

- internal/core/commands/sync_vin_numbers.go
- internal/core/commands/sync_vin_numbers_test.go
- internal/core/queries/decode_vin_test.go
- internal/infrastructure/db/migrations/20230222193908_alter_vin_number_columns.sql
> Device definition api vin numbers bug

- cmd/device-definitions-api/sync.go
- internal/core/commands/create_dd.go
- internal/core/commands/sync_vin_numbers.go
- internal/core/queries/decode_vin.go
- internal/core/queries/decode_vin_test.go
- internal/infrastructure/db/migrations/20230223123411_alter_vin_number_add_provider_source.sql
- internal/infrastructure/db/models/vin_numbers.go
- internal/infrastructure/db/repositories/device_definition_repo.go
- internal/infrastructure/db/repositories/device_definition_repo_test.go
- internal/infrastructure/db/repositories/mocks/device_definition_repo_mock.go
- internal/infrastructure/db/repositories/vin_repo.go
> decode_provider added to vin_numbers

- internal/core/models/vin_decoding_models.go
- internal/core/queries/decode_vin.go
- internal/core/queries/decode_vin_test.go
- internal/core/services/vin_decoding_service.go
- internal/core/services/vin_decoding_service_test.go
- internal/infrastructure/gateways/drivly_api_service.go
- internal/infrastructure/gateways/mocks/drivly_api_service_mock.go
- internal/infrastructure/gateways/vincario_api_service.go
- internal/infrastructure/gateways/vincario_api_service_test.go
run on prod and analyze data and then go through and make tweaks to code so we get better results
> PLA-1030 vin decoding tweaks to logging, style, externalid

- cmd/device-definitions-api/migrate_sub_command.go
- internal/api/api.go
- internal/core/commands/create_di.go
- internal/core/commands/create_di_test.go
- internal/core/queries/decode_vin.go
- internal/core/services/vin_decoding_service.go
- internal/infrastructure/gateways/drivly_api_service.go
Added Remove Cache in Create DI
> Device definition api fix create di

- cmd/device-definitions-api/populate_device_features_sub_command.go
- internal/core/common/utils.go
we want explorer and other systems that care about vehicle feature support with autopi to reflect accurate compatibility. 
Since we're now able to calculate range, we're adding a special override so that for the range feature we mark it as supported if we're able to calculate it.
> PLA-1055 add logic to mark range as supported if we're able to calculate it

- internal/core/queries/decode_vin.go
> [fix] add logs for more comprenhensive error analysis

- internal/core/commands/bulk_validate_vin.go
- internal/core/queries/decode_vin.go
> Bulk logger

- internal/api/api.go
- internal/api/handlers/device_definition_handler.go
- internal/api/handlers/device_makes_handler.go
- internal/core/queries/decode_vin.go
- internal/core/queries/decode_vin_test.go
- internal/core/services/cache_dd.go
- bug fix, don't set style id if we don't actually have it. was not a blocking bug for users, but means we'd loose out on that data.
> PLA-1197 don't set style id if don't get it

- README.md
- internal/core/models/vin_decoding_models.go
- internal/core/queries/decode_vin.go
- internal/core/queries/decode_vin_test.go
- internal/core/services/vin_decoding_service.go
- internal/infrastructure/db/migrations/20230322133859_vin_decode_raw.sql
- internal/infrastructure/db/models/vin_numbers.go
> persist raw decode data

- internal/core/queries/decode_vin.go
- internal/infrastructure/gateways/drivly_api_service.go
> PLA-1228 - Device definitions api vin observability

- internal/core/services/vin_decoding_service.go
- internal/infrastructure/gateways/vincario_api_service.go
- add metadata to dd from vincario
> [PLA-1084] add metadata to dd from vincario

- go.mod
- internal/api/grpc_definitions_service.go
- internal/api/handlers/integration_handler.go
- internal/core/queries/decode_vin.go
- internal/core/queries/get_in_by_id.go
- internal/core/queries/get_in_by_id_test.go
- internal/infrastructure/gateways/drivly_api_service.go
> PLA-1444 - Device definitions api fix get integration by

- charts/device-definitions-api/templates/cronjob.yaml
- charts/device-definitions-api/values-prod.yaml
- cmd/device-definitions-api/populate_device_features_sub_command.go
- cmd/device-definitions-api/sync_sub_command.go
- support an array of jobs
- fix populate device features job
- remove wget stuff that did not work
> PLA-1201 re-work jobs, and fix failing job

- charts/device-definitions-api/templates/cronjob.yaml
- charts/device-definitions-api/values-prod.yaml
> PLA-1201 fix jobs yaml

- internal/core/commands/create_dd.go
- internal/core/commands/create_dd_test.go
- internal/core/queries/decode_vin.go
- internal/infrastructure/db/repositories/device_definition_repo.go
- internal/infrastructure/db/repositories/device_definition_repo_test.go
- internal/infrastructure/db/repositories/mocks/device_definition_repo_mock.go
> PRO-1413 - use transaction for vin decode

- go.mod
- go.sum
- internal/core/commands/update_dd.go
> remove some unused code

- cmd/device-definitions-api/sync_sub_command.go
- internal/api/api.go
- internal/core/queries/decode_vin.go
- internal/core/queries/decode_vin_test.go
- internal/core/services/mocks/vin_decoding_service_mock.go
- internal/core/services/vin_decoding_service.go
- internal/core/services/vin_decoding_service_test.go
- internal/infrastructure/dbtest/test_helper.go
> PRO-1785 - Return Default DD

- internal/api/api.go
- internal/api/grpc_definitions_service.go
- internal/core/models/device_style_models.go
- internal/core/queries/get_ds_by_id.go
- internal/core/services/vin_decoding_service.go
> PRO-1878 - add device attribute to device style

- internal/core/queries/get_ds_by_id.go
- internal/core/queries/get_ds_by_id_test.go
can now set powertrain from style metadata
> SM-73 rework and tests for get device style - powertrain

- internal/core/queries/get_ds_by_id.go
> SM-2 tweaks to getting style PT

- internal/core/queries/decode_vin.go
> SM-121/ - Validate posible nil

- internal/core/commands/nhtsa_recalls_test.go
- internal/core/commands/update_dd_test.go
- internal/infrastructure/db/repositories/vin_repo.go
- internal/infrastructure/dbtest/test_helper.go
> Change WMI Query

- internal/infrastructure/gateways/datgroup_api_service.go
> add datgroup request response log

- internal/core/queries/decode_vin.go
> fail decoding if name has a comma

- cmd/device-definitions-api/main.go
- cmd/device-definitions-api/update_device_definition_slug_sub_command.go
> SM-815 - Sync Slug

- cmd/device-definitions-api/update_device_definition_slug_sub_command.go
- internal/core/common/utils.go
- internal/infrastructure/db/repositories/device_definition_repo.go
> Add func slug

- internal/core/common/utils.go
- internal/core/common/utils_test.go
> Validate comma

- internal/core/queries/decode_vin.go
- internal/core/services/vin_decoding_service.go
- internal/core/services/vin_decoding_service_test.go
> SM-811 refactor model and year validations, logging tweaks

- internal/core/services/vin_decoding_service.go
- internal/infrastructure/gateways/datgroup_api_service.go
> Sm-811 country for datgroup default to DE

- go.mod
- internal/core/services/vin_decoding_service.go
- internal/core/services/vin_decoding_service_test.go
- internal/infrastructure/gateways/datgroup_api_service.go
> [SM-911] add more validations for DAT group vin decoding

- internal/api/api.go
- internal/infrastructure/gateways/device_definition_on_chain_service.go
> SM-962 - Add Metrics

- cmd/device-definitions-api/sync_device_definition_search.go
- internal/core/queries/get_dd_by_search.go
> SM-1018 - Device definitions=api add tokenid search

- internal/api/handlers/smartcar_oems.json
- Enable Dacia & Porsche
- Remove Ford
> MOB-2035, MOB-2016, MOB-2097: Enable Dacia & Porsche, Remove Ford popular tag.

- internal/core/commands/create_dd.go
- internal/core/commands/create_dd_test.go
- internal/core/commands/device_type_vehicle_properties.json
> fix powertrain required bug when not a vehicle

- internal/core/common/constants.go
- internal/infrastructure/gateways/device_definition_on_chain_service.go
> set the device type correctly for on chain trx

- cmd/device-definitions-api/main.go
- internal/api/grpc_definitions_service.go
- internal/config/settings.go
- internal/core/queries/decode_vin.go
- internal/infrastructure/gateways/device_definition_on_chain_service.go
- internal/infrastructure/gateways/mocks/device_definition_on_chain_service_mock.go
> implement script for loading csv with dd's

- charts/device-definitions-api/templates/secret.yaml
- cmd/device-definitions-api/bulk_create.go
- internal/api/handlers/device_definition_handler.go
- internal/config/settings.go
- internal/core/queries/decode_vin.go
> implement waiting for trx to finish

- internal/api/api.go
- internal/api/handlers/device_definition_handler.go
- internal/api/routes.go
- internal/core/queries/get_r1_compat_search.go
- internal/infrastructure/search/typesense_search_service.go
- implement r1 compatibility search
- a little sloppy
> SM-1258 implement r1 search

- internal/infrastructure/search/typesense_search_service.go
> fix facets from bad refactor

- internal/core/queries/decode_vin.go
- use the modelslug when doing the tableland lookup
- refactor a few places where we were using the model slug
I don't think this should impact much as we were still doing the web2 db lookup for the device definition and this error log was put in place to detect possible issues with the next migration step.
> use modelSlug

- internal/infrastructure/gateways/device_definition_on_chain_service.go
> Improve performance of get device definition

- cmd/device-definitions-api/sync_r1_compatibility.go
> change to use google sheets handler to get sheet data for r1 sync

- docker-compose.yml
- go.mod
- go.sum
- internal/infrastructure/dbtest/test_helper.go
> Bump Postgres to 16.6

- cmd/device-definitions-api/add_vin.go
- internal/core/queries/decode_vin.go
- internal/core/queries/decode_vin_test.go
- internal/infrastructure/db/migrations/20250502151154_wmi_manufacturer.sql
- internal/infrastructure/db/models/device_makes.go
- internal/infrastructure/db/models/wmis.go
- internal/infrastructure/db/repositories/vin_repo.go
- internal/infrastructure/dbtest/test_helper.go
> INTG-1696 wmi mismatch handling

- internal/api/handlers/device_definition_handler.go
> handle invalid definition id's correctly

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/api/api.go
- internal/api/handlers/device_definition_handler.go
- internal/api/routes.go
- internal/core/queries/get_vin_profile.go
> INTG-1747: implement new endpoint to get vin profile info

- internal/api/api.go
- internal/core/queries/get_vin_profile.go
> Add powertrain type to vin profile using existing logic
